# Generated by Django 3.0.5 on 2020-05-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
