# Generated by Django 3.0.5 on 2020-05-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200501_2131'),
    ]
#表示迁移脚本做的什么事情
    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='create_time',
        ),
    ]
