# Generated by Django 3.0.5 on 2020-04-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='removed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
