# Generated by Django 3.0.5 on 2020-04-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200408_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='signature',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
