# Generated by Django 3.0.5 on 2020-04-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_person_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
