# Generated by Django 3.0.5 on 2020-04-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
