# Generated by Django 3.0.5 on 2020-04-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20200408_2017'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='article_author',
        ),
    ]
