# Generated by Django 3.0.5 on 2020-04-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20200408_2019'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
