# Generated by Django 3.0.5 on 2020-04-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(related_name='articles', to='article.Article'),
        ),
    ]
